// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwKrwoJzsBa_zmvexeZH2DW6MXQR0QNIw',
    appId: '1:404003738267:web:31ef466b7e6d68ac35ac3e',
    messagingSenderId: '404003738267',
    projectId: 'e-commerce-book-shop',
    authDomain: 'e-commerce-book-shop.firebaseapp.com',
    storageBucket: 'e-commerce-book-shop.appspot.com',
    measurementId: 'G-RZNNL55PPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUVIUMcOy1nHl7qiKxDen_YcW6pmdeyMg',
    appId: '1:404003738267:android:e9d58f6d5994683735ac3e',
    messagingSenderId: '404003738267',
    projectId: 'e-commerce-book-shop',
    storageBucket: 'e-commerce-book-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC82qmSP9vXOT3Z9uA6wX1OODme0smiSDQ',
    appId: '1:404003738267:ios:ce26885437df513f35ac3e',
    messagingSenderId: '404003738267',
    projectId: 'e-commerce-book-shop',
    storageBucket: 'e-commerce-book-shop.appspot.com',
    iosBundleId: 'com.example.bookShop',
  );
}
